"""empty message

Revision ID: 5e1992e4749c
Revises: 
Create Date: 2020-09-12 04:27:24.649236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e1992e4749c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Content',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('passWord', sa.String(length=400), nullable=True),
    sa.Column('webPage', sa.String(length=160), nullable=True),
    sa.Column('link', sa.String(length=5000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=300), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=True),
    sa.Column('email', sa.String(length=400), nullable=True),
    sa.Column('encryption_key', sa.String(length=160), nullable=True),
    sa.Column('api_key', sa.String(length=500), nullable=True),
    sa.Column('first_name', sa.String(length=500), nullable=True),
    sa.Column('last_name', sa.String(length=500), nullable=True),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('encryption_key'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('Content')
    # ### end Alembic commands ###
